### ISSUE TITLE
is NDI useful ?

### ISSUE THREAD

**Issue by gedw99** [datarhei/gosrt#71]
Hey @ioppermann 

SRT and NDI are for different things, and I was wondering what your thoughts are on each ?

I use Video Mixing hardware / software, but not really uo with the Visio of Restreamer and if NDI is useful ?

**Comment by ioppermann** [comment]
SRT and NDI both offer a solution for low-latency live video/audio transport and both are IP based.

NDI uses its own format with or without H264 and HEVC encoding in their latest format and is meant for a well connected studio environment. I don't know how resilient NDI is towards packet loss or a bad wifi connection.

SRT is data agnostic. With SRT you can send anything you want. For video/audio transport you usually use the mpegts container. I has mechanisms for error correction and resending data in case it gets damaged or lost, and it will also drop data in case it arrives too late.

Because NDI is proprietary, we prefer SRT which is an open standard.
