### ISSUE TITLE
How to save streams to disk?

### ISSUE THREAD

**Issue by maxogden** [datarhei/gosrt#9]
For example, can you have a server that writes each new stream to a .ts file, creating a new file each time based on a value in the query string plus the date?

**Comment by ioppermann** [comment]
Yes, this is possible. Your starting point would be the `srt.Server{}` struct, where you implement and provide `handleConnect` and `handlePublish` functions. The `handleSubscribe` function is not required and may simply close the connection.

`handleConnect` has to check if the incoming connection will publish (e.g. send) a stream to the server. There you can verify the `streamid` in order to implement some access control. Then you return either `srt.REJECT` or `srt.PUBLISH`.

Returning `srt.PUBLISH` will cause the `handlePublish` to be called in its own goroutine. It provides you with a `srt.Conn` instance where you can read from until error (e.g. connection closed from the sender side) and write the data to the disk. It might look like this (just a rough sketch):

```
func handlePublish(conn srt.Conn) {
    defer conn.Close()

   // open .ts file
   file, err := os.Create(...)
   defer file.Close()

   io.Copy(file, conn)
}
```
